apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
   type: local
spec:
  storageClassName: "minikube-hostpath"
  capacity:
   storage: 1Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
   path: "/mnt/data"