apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: "minikube-hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
   requests: 
    storage: 1Gi
  volumeName: my-pvc