apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sinatra-rs
  labels:
    name: sinatra-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: sinatra
  template:
    metadata:
      labels:
        tier: sinatra
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3